name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android
      run: flutter build apk --release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-release
        path: build/app/outputs/flutter-apk/app-release.apk
