name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
<<<<<<< HEAD
          flutter-version: "3.10.0" # Uyumlu bir sürüm kullanın
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ">=2.18.0 <3.0.0"
=======
          flutter-version: "3.x" # Specify the version if needed
>>>>>>> c8c1d117b4a970f3f606c87c5063926c673565da

      - name: Install dependencies
        run: flutter pub get

      - name: Upgrade dependencies
        run: flutter pub upgrade

      # Uncomment this step to verify the use of 'flutter format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: |
          sudo apt-get update && sudo apt-get install -y libgtk-3-dev
          flutter test
