name: Deploy GitHub Pages

on:
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  # Job for deploying to GitHub Pages
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.3"

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - run: flutter --version

      # Build web release
      - name: Build Web Release
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          cp -r build/web/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/dikeckaan/flutter-sni-bughost-checker.git
          git push -u origin gh-pages --force
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

  # Job for updating the version
  update-version:
    if: >
      github.event.review.state == 'approved' &&
      github.event.pull_request.state == 'open'
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Update version
        run: |
          # Command to update version information, adjust as needed
          echo "Version updated after approval"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.json
          git commit -m "Update version after approval"
          git push
