name: GitHub Pages Deployment CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.3"

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - run: flutter --version

      # Build web release
      - name: Build Web Release
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
