name: GitHub Pages Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Set GitHub User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone gh-pages Branch
        run: |
          if git ls-remote --exit-code origin gh-pages; then
            git clone https://github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages
          else
            git clone https://github.com/${{ github.repository }}.git gh-pages
            cd gh-pages
            git checkout --orphan gh-pages
            git rm -rf .
            echo "This is a placeholder for GitHub Pages." > index.html
            git add index.html
            git commit -m "Initialize gh-pages branch"
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git gh-pages
          fi

      - name: Copy Build Output
        run: rsync -av --delete build/web/ gh-pages/

      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git add --all
          git commit -m "Deploy to GitHub Pages"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git gh-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
