name: iOS Release CI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.3"

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - run: flutter --version

      # Build iOS IPA
      - name: Build iOS IPA
        run: |
          flutter build ipa --release --no-codesign
          cd build/ios/archive/Runner.xcarchive/Products/Applications
          mkdir PayLoad
          mv Runner.app Payload/
          zip -r release-app.zip Payload
          mv release-app.zip release-app.ipa

      # Upload IPA as artifact
      - name: Upload release IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/ios/archive/Runner.xcarchive/Products/Applications/*.ipa
