name: iOS Release CI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Flutter instead of Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.3"

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - run: flutter --version

      # Build iOS IPA
      - name: Build iOS IPA
        run: |
          flutter build ios --release --no-codesign

      # Create Tag
      - name: Create Tag
        run: |
          git tag v$(date +%Y%m%d%H%M%S)
          git push origin --tags

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/ios/ipa/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
